Binformat
tokarevdr/BinaryT_Message_Simulator pull request #5
Opened 2023-06-25 12:01 UTC by pavelko294

Добавлены форматы BIN16, BIN32. BIN32 нужно проверить.

2023-06-25 12:15 UTC, tokarevdr requested changes
Описание надо разделить на 2 отдельных класса "bin16" и "bin32", т.е. 4 файла (2 .cpp и 2 .h).
Методы в них должны называться одинаково.
Надо добавить проверки на вводимые в методах значения (если я попытаюсь ввести бит с номером 100 и т.д. везде).
Методы SetBit() сделаны неправильно

2023-06-25 12:43 UTC, tokarevdr requested changes
В bin32.cpp методы не переименованы

2023-06-25 13:23 UTC, tokarevdr requested changes

2023-06-25 13:23 UTC, tokarevdr commented on src/main/bin16.cpp
> +    if (bit >= 0 && bit <= 15){
Заменить на проверку не вхождения в диапазон с return

2023-06-25 13:23 UTC, tokarevdr commented on src/main/bin16.cpp
> +    if(buffer >= 0 && buffer <= 65535)
Убрать

2023-06-25 13:23 UTC, tokarevdr commented on src/main/bin16.cpp
> +    else qDebug() << "Inserted bit is out of range";
Или возвращать false и выводить qDebug() или сделать exception

2023-06-25 13:23 UTC, tokarevdr commented on src/main/bin16.cpp
> +    else return "Inserted bit is out of range";
Изменить формат вывода сообщений

2023-06-27 16:28 UTC, Alexey020602 approved these changes

2023-06-27 17:36 UTC, tokarevdr approved these changes

2023-06-27 17:36 UTC, merged